### ISSUE TITLE
bg_map in backward.cu

### ISSUE THREAD

**Issue by BigCiLeng** [gapszju/3DGS-DR#11]
https://github.com/gapszju/3DGS-DR/blob/4077f1d4b45891885e6ebd1089da7bc51bee8afc/submodules/diff-gaussian-rasterization_c7/cuda_rasterizer/backward.cu#L554

i wonder if this should be modified or not as the code use a (3 h w) bg_map in alpha-blending process, (it may have little influence on the grad?

**Comment by YessionCC** [comment]
The bg_map has no impact at all. It's just my previous modification.

**Comment by BigCiLeng** [comment]
ok i see, thanks for your reply
