### ISSUE TITLE
prolem about psnr in paper

### ISSUE THREAD

**Issue by Gragonfly** [gapszju/3DGS-DR#15]
Hello, I would like to know the command to run the sedan scene in the paper and the image resolution used during runtime. I am using a 4070 16G and 1/4 resolution, but it seems I cannot achieve such a high PSNR as in the paper.

**Comment by YessionCC** [comment]
We used 1/8 resolution in the sedan scene.

**Comment by Gragonfly** [comment]
thx!!!
