### ISSUE TITLE
ModuleNotFoundError: No module named 'diff_gaussian_rasterization_c4'

### ISSUE THREAD

**Issue by jpsml** [gapszju/3DGS-DR#2]
I tried to run the code with the following command:

python -u train.py -s data/nerf_synthetic/mic --eval --iterations 61000 --white_background --densification_interval_when_prop 100

Then I got the following error:

Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from gaussian_renderer import render, render_env_map
  File "/home/jpsml/3DGS-DR/gaussian_renderer/__init__.py", line 16, in <module>
    import diff_gaussian_rasterization_c4
ModuleNotFoundError: No module named 'diff_gaussian_rasterization_c4'

**Comment by jpsml** [comment]
In order to run it, you just need to remove the following line in gaussian_renderer/__init__.py:

import diff_gaussian_rasterization_c4

**Comment by gapszju** [comment]
Thanks. We have fixed it.
