### ISSUE TITLE
How to use custom data？use colmap？

### ISSUE THREAD

**Issue by ch1998** [gapszju/3DGS-DR#4]
Can I use colmap to create training data like 3dgs?

**Comment by YessionCC** [comment]
Of course. The only additional required parameter is to provide the spherical bounds of the foreground object. Please refer to the command lines for real scenes (sedan/toycar) in the `train.sh` file.

**Comment by ch1998** [comment]
> Of course. The only additional required parameter is to provide the spherical bounds of the foreground object. Please refer to the command lines for real scenes (sedan/toycar) in the `train.sh` file.

Thanks for reply!
the parameters --env_scope_center -0.032 0.808 0.751 --env_scope_radius 2.138 in cmd ’-s data/ref_nerf/ref_real/sedan --eval --iterations 61000 --longer_prop_iter 36_000 --use_env_scope --env_scope_center -0.032 0.808 0.751 --env_scope_radius 2.138‘  seem to be very special.Is it selected after multiple attempts or is there some way to calculate it precisely?

**Comment by YessionCC** [comment]
This is a rough spherical bound that can enclose the sedan car. Our method does not require an precise boundary. Just make a rough sphere bound is ok.

**Comment by ch1998** [comment]
I will try! Thanks!
