### ISSUE TITLE
about train time

### ISSUE THREAD

**Issue by ch1998** [gapszju/3DGS-DR#5]
In the paper, the modeling of the real scene in table 3 is 47min, but it took me 2 and a half hours to train a  sence having 110 2k images. Is this time correct?

the commod ：python -u train.py -s data/GS/car/ --eval --iterations 61000 --longer_prop_iter 36_000 --use_env_scope --env_scope_center -0.032 0.808 0.751 --env_scope_radius 2.138

use single 3090

**Comment by gapszju** [comment]
We use  the 1/4 resized images for training.
