### ISSUE TITLE
Noisy normal map in nerf_synthetic "materials" scene

### ISSUE THREAD

**Issue by jpsml** [gapszju/3DGS-DR#6]
I executed the following experiment:

python -u train.py -s data/nerf_synthetic/materials/ --eval --iterations 61000 --white_background --densification_interval_when_prop 100

However, the obtained normal maps are a little bit noisy in the spheres with high specularity:

![train_view_r_2_normal_map](https://github.com/gapszju/3DGS-DR/assets/13179144/56ec5da4-728e-4a14-b204-75c3c511a7ca)

I noticed that  the obtained env maps are a little bit blurred:

![env_cood1](https://github.com/gapszju/3DGS-DR/assets/13179144/3be6f0d5-15a2-4674-91f4-236175b07ce3)
![env_cood2](https://github.com/gapszju/3DGS-DR/assets/13179144/2602f73b-965d-4e9c-9d90-8fd6893f9f5e)

Is this the expected result?

**Comment by YessionCC** [comment]
Our method does not model different roughness level and interreflections. Our method tends to first fit reflections with higher roughness, so the env. map looks a little bit blurred. Additionally, interreflections can affect normal reconstruction, resulting in poorer performance in the material scene.
